### ISSUE TITLE
Push website hosting to S3 bucket

### ISSUE THREAD

**Issue by GUI** [GUI/covid-vaccine-finder#10]
The website is currently hosted via GitHub pages. But pushing to the `gh-pages` branch every minute may not be a particularly viable long-term solution given the number of commits and frequency of pushes (there's also a lot of churn in the files, since all the JSON changes are recorded every minute). I've read about GitHub Pages build limits per day, although I'm not sure that affects us, since we're not actually building the site with GitHub pages (with Jekyll), just pushing an already built site to the branch. I received a couple GitHub Page build failure notifications last night, which is maybe related to all this. In any case, I guess it seems like just pushing to an S3 bucket might be a better plan so we don't abuse GitHub Pages.

**Comment by J-Swift** [comment]
Great project! My sister lives in Denver and brought it to my attention. Really glad you open sourced it.

I have a somewhat similar architecture that I use for a project here (https://github.com/J-Swift/cod-stats) if you want to take a look at how I'm pushing to s3. I do both an rsync diff (https://github.com/J-Swift/cod-stats/blob/master/frontend/generate_lookup_data.sh#L974) as well as s3 diff (https://github.com/J-Swift/cod-stats/blob/master/deploy/deploy.sh#L26) to be maximally efficient on my deploys and it works out well.

I'm happy to help if I find time but I'm in the middle of moving so doubt there will be a ton available in the immediate term.

**Comment by GUI** [comment]
Thanks so much, @J-Swift!

Things are now switched over to S3. I'm still pushing things into GH Pages for history, but I may disable that, since the commit count is becoming a bit ridiculous (or at least shift it into another repo, so this one isn't so bogged down).

Switching to S3 may also have the benefit of allowing us to set the `Cache-Control` headers on the pages, which may prevent issues of users seeing stale data I've heard of.
