### ISSUE TITLE
Expand Pharmaca scanning to other states

### ISSUE THREAD

**Issue by GUI** [GUI/covid-vaccine-finder#20]
This is a smaller regional pharmacy, but they are in a number of other states. As part of this, also need to move this data into The PostgreSQL format to better standardize things.

**Comment by GUI** [comment]
Done!

**Comment by jxchong** [comment]
Your WA api json for this chain seems to be funky.

**Comment by GUI** [comment]
@jxchong: Do you have details on what seems to be wrong? Sorry the API isn't really documented at this point, but any appointments should show up in the `"appointments"` array part of each store. If you're seeing funky things in the `"appointments_raw"` portion of the JSON data, that's more just for debugging purposes, and that's the direct response data I'm getting back from the providers before parsing (which in Pharmaca's case is HTML data that needs to be parsed). Let me know if you're seeing something more specifically wrong, though!

**Comment by jxchong** [comment]
Ahh ok yeah it's the appointments_raw section that is huge compared to the other chains.
